{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "velflix.fullname" . }}
  labels:
    {{- include "velflix.labels" . | nindent 4 }}
  # namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: {{  .Values.ingress.host  }}
      http:
        paths:
          - path: {{  .Values.ingress.path  }}
            pathType: {{  .Values.ingress.pathType  }}
            backend:
              service:
                name: {{ include "velflix.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}