apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-db
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: mysql-db
  serviceName: "mysql-db"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql
        image: {{ .Values.mysql.image }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql.Password }}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.database }}
        ports:
        - containerPort: 3306
          name: mysql
        args: ["--default-authentication-plugin=mysql_native_password"]  
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 1Gi
