apiVersion: v1
kind: Secret
metadata: 
  name: {{ include "job-app.fullname" . }}
  # namespace: {{ .Values.namespace }}
immutable: false
type: Opaque
data:
  password: {{ .Values.env.password | quote  }}