 alertmanager:
      # alertmanagerSpec:
      #   replicas: 2
      #   podAntiAffinity: "hard"
      config:
        global:
          slack_api_url: "https://talk.improwised.com/hooks/91rz8cc69bgftgrqgwh5dx988e"
        route:        
          receiver: 'slack'
          routes:
          - receiver: 'slack'
            matchers:
              - alertname =~ "Watchdog"
        receivers:
        - name: 'slack'
          slack_configs:
          - channel: '#demo-alerting' # channel of prometheus alert
            send_resolved: true
            # title: 'urgent action needed Instance is down'
            title: '{{ .CommonAnnotations.summary }}'