groups:
  - name: Instance-down
    rules:
    - alert: InstanceDown
      expr: up == 0 and (namespace == "demo-flux")
      labels:
        severity: critical
      for: 1m
      annotations:
        summary: 'Instance is down'

