apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pojok-lelang.fullname" . }}
  labels:
    {{- include "pojok-lelang.labels" . | nindent 4 }}
  # namespace: {{ .Values.namespace }}
spec:
  replicas: {{  .Values.replicaCount  }}
  selector:
    matchLabels:
      {{- include "pojok-lelang.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pojok-lelang.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- toYaml .Values.env | nindent 10 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP