apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pojok-lelang.fullname" . }}
  labels:
    {{- include "pojok-lelang.labels" . | nindent 4 }}
  # namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: {{  .Values.ingress.host  }}
      http:
        paths:
          - path: {{  .Values.ingress.path  }}
            pathType: {{  .Values.ingress.pathType  }}
            backend:
              service:
                name: {{ include "pojok-lelang.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
