apiVersion: v1
kind: Service
metadata:
  name: mysql-db
  namespace: job-app-management
  labels:
    app: mysql-db
spec:
  ports:
    - port: 3306
      name: mysql
  clusterIP: None
  selector:
    app: mysql-db
