version: '3.9'

services:
  app:
    build: .
    container_name: job_app_management_app
    depends_on:
      - db
    environment:
      DB_HOST: 127.0.0.1
      DB_DATABASE: apply
      DB_USERNAME: root
      DB_PASSWORD: 12345678
    ports:
      - "8000:8000"


  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: apply
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
    ports: 
      - "3306:3306"
