# Default values for polymorphic-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# helm:
#   dependencies:
#   - name: mysql
#     version: 11.1.9
#     repository: https://charts.bitnami.com/bitnami
#     condition: mysql.enabled



nameOverride: ""
fullnameOverride: ""
prefixWithReleaseName:
  enabled: true
image:
  repository: chandanteekinavar/docker-exercise-app
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []

volumeMounts: []

volumes: []


# env:
#   dbHost: "db"
#   dbPort: "3306"  
#   database: "apply"
#   dbUsername: "root"
#   password: "MTIzNDU2Nzg="

env:
  - name: DB_HOST
    value: "db
  - name: DB_PORT
    value: "3306"  
  - name: DB_DATABASE
    value: "apply"
  - name: DB_USERNAME
    value: "root"
  - name: DB_PASSWORD
    value: "12345678"

envFrom: []

services:
  - name: job
    image:
    averageUtilization: 50
    ## initContainers:
    ##   - name: something
    ##     image: alpine
    ##     command: ['command', 'here']

    initContainers: []

    lifecycleHooks: {}

    healthcheck:
      enabled: false
      type: httpGet
      # path: /healthz
      # port: http
      # initialDelaySeconds: 30
      # periodSeconds: 30

    autoscaling: false
    minReplicaCount: 1
    maxReplicaCount: 1
    env: []
    envFrom: []
    ports:
    - name: http
      containerPort: 8000
      protocol: TCP
    resources: {}
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      # limits:
      #  cpu: 100m
      #  memory: 128Mi
      # requests:
      #  cpu: 100m
      #  memory: 128Mi
    securityContext: {}
      # fsGroup: 1001
      # runAsGroup: 1001
      # runAsUser: 1001
    dnsConfig: {}
      # nameservers:
      #   - 192.0.2.1 # this is an example
      # searches:
      #   - ns1.svc.cluster-domain.example
      #   - my.dns.search.suffix
      # options:
      #   - name: ndots
      #     value: "2"
      #   - name: edns0
    annotations: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    volumeMounts: []
    volumes: []

    service:
      enabled: true
      # className: nginx
      type: ClusterIP
      ports:
      - name: http
        port: 80
        targetPort: 8000
        protocol: TCP
      annotations: {}

    # ingress:
    #   enabled: true
    #   # className: nginx
    #   annotations: {}
    #   hosts:
    #     - host: job-app.com
    #       paths: 
    #         path: "/"
    #         pathType: Prefix
          
    ingress:
      enabled: true
      annotations: {}
      hosts:
        - host: job-app.com
          paths:
            - path: "/"
              pathType: Prefix
              serviceName: http
              servicePort: 80

