name: job-app-ci

on:
  push:
    branches:
      - ci

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build and Push Docker Image
      #   run: |
      #     docker build -f docker-exercise/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/docker-exercise-app:2.1
      #     # docker tag ${{ secrets.DOCKER_USERNAME }}/docker-exercise:latest ${{ secrets.DOCKER_USERNAME }}/docker-exercise:${GITHUB_SHA}
      #     docker push ${{ secrets.DOCKER_USERNAME }}/docker-exercise-app:2.1 .
      #     # docker push ${{ secrets.DOCKER_USERNAME }}/docker-exercise:${GITHUB_SHA}

      - name: Set up Environment Variables
        id: vars
        run: |
          # Get the branch name
          BRANCH_NAME=${GITHUB_REF##*/}
          # Get the commit SHA (truncated to 8 characters)
          COMMIT_SHA=${GITHUB_SHA:0:8}
          # Get the current timestamp in the desired format
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
          echo "COMMIT_SHA=${COMMIT_SHA}" >> $GITHUB_ENV
          echo "TIMESTAMP=${TIMESTAMP}" >> $GITHUB_ENV 
          IMAGE_TAG="${BRANCH_NAME}-${COMMIT_SHA}-${TIMESTAMP}"    
                        
              
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          file: docker-exercise/Dockerfile
          context: docker-exercise
          push: true
          # tags: ${{ secrets.DOCKER_USERNAME }}/docker-exercise-app:${{ github.event.branch }}-$( git rev-parse --short HEAD ) - ${{ env.NOW }}
          tags: ${{ secrets.DOCKER_USERNAME }}/docker-exercise-app:$IMAGE_TAG